# Generated by Django 5.2 on 2025-07-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_origen', models.CharField(max_length=20)),
                ('cuenta_destino', models.CharField(max_length=20)),
                ('cooperativa_origen', models.CharField(max_length=100)),
                ('cooperativa_destino', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, default=0.41, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
